import discord
from dotenv import load_dotenv
from os import getenv
from discord.ext import bridge, tasks
from itertools import cycle
import google.generativeai as palm
from pathlib import Path

#######################################################
# Pre-startup checks and initializations
#######################################################

if not Path("dev.env").is_file():
    raise Exception("dev.env file is missing. Please create one and try again.")

load_dotenv("dev.env")

if getenv("PALM_API_TOKEN") is None or getenv("PALM_API_TOKEN") == "INSERT_API_KEY":
    raise Exception("PALM_API_TOKEN is not configured in the dev.env file. Please configure it and try again.")

palm.configure(api_key=getenv("PALM_API_TOKEN"))

if getenv('TOKEN') is None:
    raise Exception("TOKEN is not configured in the dev.env file. Please configure it and try again.")

#######################################################
# Runtime variables
#######################################################
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = bridge.Bot(command_prefix="cb!", intents = intents)

#######################################################
# Events and tasks
#######################################################

statuses = cycle([
    "Crash Bandicoot",
    "Crash Bandicoot 2: Cortex Strikes Back",
    "Crash Bandicoot 3: Warped",
    "Crash Team Racing",
    "Crash Bandicoot N. Sane Trilogy",
    "Crash Team Racing Nitro-Fueled",
    "Crash Bandicoot 4: It's About Time"
])

#https://stackoverflow.com/a/65780398
@tasks.loop(seconds=180)
async def change_status():
    await bot.change_presence(activity=discord.Game(next(statuses)))

#######################################################
# CONTEXTUAL MEMORY
#######################################################
messages = []

@bot.event
async def on_ready():
    print(f"{bot.user} is ready and online!")
    change_status.start()

@bot.event
async def on_message(message):
    if message.author == bot.user:
        return

    # Debug
    print(type(message.content))
    print(message.content)
    if str(message.content).upper().startswith("HEY CRASH"):
        if len(message.content.split(" ")) < 3:
            await message.channel.send(f"Hey {message.author.mention}, I'm Crash Bandicoot!")
            return

        prompt = " ".join(message.content.split(" ")[2:])
        messages.append(prompt)
        response = palm.chat(
            model="models/chat-bison-001",
            temperature=0.25,
            candidate_count=1,
            top_k=40,
            top_p=0.95,
            context="Be and act as Crash Bandicoot",
            messages=messages
        )

        embedmsg = False
        answer = None
        if len(response.last) > 2000:
            embedmsg=True
            answer = discord.Embed(
                title="Crash Bandicoot",
                description=response.last,
                color=discord.Color.orange()
            )
            answer.set_footer(text="Responses generated by AI may not be accurate")

        if embedmsg:
            await message.channel.send(embed=answer)
        else:
            await message.channel.send(response.last)
        messages.append(response.last)


#######################################################
# FUNCTIONS
#######################################################
@bot.slash_command()
async def clearmemory(ctx):
    """Clear Crash's memory"""
    if len(messages) == 0:
        await ctx.respond("Memory is already clear!")
        return

    messages.clear()
    await ctx.respond("Memory cleared!")

@bot.slash_command()
async def listconvos(ctx):
    """List all conversations in Crash's memory"""
    if len(messages) == 0:
        await ctx.respond("Memory is empty!")
        return

    memory = ". ".join(messages)
    
    if len(memory) > 2000:
        await ctx.respond("Memory is too large to display!")
        return

    await ctx.respond(memory)

bot.run(getenv('TOKEN')) 
